[workspace]
resolver = "2"
members = [
  "deduped-dashmap",
  "merino-adm",
  "merino-cache",
  "merino-integration-tests-macro",
  "merino-integration-tests",
  "merino-suggest",
  "merino-web",
  "merino",
]

[profile.release]
# Enables line numbers in Sentry reporting
debug = 1
